### PR TITLE
Implemented getters for ColumnApi, GridApi, and RowModel for RowNode class.

### PR DESCRIPTION
**Pull request by wenkepaul**
Implemented getColumnApi, getGridApi, and getRowModel for RowNode class.

### CODE REVIEW

**Comment by wenkepaul** [comment]
Not stale.  I reimplemented the three getters in their new file location.

**Comment by wenkepaul** [comment]
Not stale.  Fixed merge conflicts.

**Comment by wenkepaul** [comment]
Not stale.

**Comment by wenkepaul** [comment]
Not stale.

**Comment by wenkepaul** [comment]
Any update on this?

**Comment by wenkepaul** [comment]
Not stale.

**Comment by rmc-software** [comment]
Hi - this change doesn't fit with our interface design. We supply the grid and column api's in the various grid callbacks. Perhaps we've overlooked one of these callbacks. Can you explain the issue you're trying to overcome with the introduction of these getters?

**Comment by wenkepaul** [comment]
We have a bunch of utility functions which accept a RowNode object.  There's a new requirement where given a RowNode, I need to be able to compare this row's data to its siblings.  In order to access the GridApi's `forEachNode` function, I first need access to the RowNode's gridApi property.

**Comment by rmc-software** [comment]
The api's are global and not specific to the model of row. I can't get into the specifics of your application but you should access the api's in a different way and supply them along with the RowNode to your utility methods. If you are a customer you can contact our support team via zendesk where they can help you with your application. In the meantime I'm going to close this PR.

**Pull request closed without merging**
