### PR TITLE
Enumerate DomLayout options

### PR DESCRIPTION
**Pull request by spawnia**
This documents https://www.ag-grid.com/javascript-grid-width-and-height/#dom-layout as part of the types.

### CODE REVIEW

**Comment by spawnia** [comment]
Updated the PR, can i get any feedback?

**Comment by spawnia** [comment]
Still relevant.

**Comment by spawnia** [comment]
I am not giving up.

**Comment by ag-grid-shared** [comment]
@spawnia :-) I'll raise it with the team - thanks for your persistence

**Comment by rmc-software** [comment]
Even though the stale bot has closed this, rest assured it has been noted. We haven't merged it just yet as we will be doing a full review of our interfaces in the next 1-2 releases and we'd prefer do address all properties in one go.

**Comment by spawnia** [comment]
Here we go again.

**Comment by rmc-software** [comment]
Still scheduled for v23.1.

**Pull request closed without merging**
