### PR TITLE
Removing deprecated division symbol

### PR DESCRIPTION
**Pull request by lounsbrough**
This PR resolves https://github.com/ag-grid/ag-grid/issues/4543

This is the result of running `sass-migrator division **/*.scss`

https://www.npmjs.com/package/sass-migrator

### CODE REVIEW

**Comment by TheSeg** [comment]
Switching to multiplication where possible is the right move. The only issue with the approach using `math.div` is that Libsass projects will break. While the best choice for everyone is to move away from Libsass, using `math.div` is more breaking than meets the eye.

The Bootstrap project solved this situation by creating a custom `divide()` function for these situations. That way you still get division while not requiring `@use "sass:math";`. Everyone wins!

* [Bootstrap `devide()` PR](https://github.com/twbs/bootstrap/pull/34245)
* Bootstrap's `divide()` function:
https://github.com/twbs/bootstrap/pull/34245/files#diff-de6111a37eb67d027961043ce738e80a3ac4ad61a6e7704d35cb3168369cba01R223

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for submitting this PR, at the moment we don’t have a safe mechanism to automatically merge these, but we do this manually instead.

At this stage, your PR is being considered, we should update you as soon as possible, if this PR were to be approved note that we would do this in our end manually and we would close this, but you would get your changes effectively into our source code.

At the moment this is going to be flagged with ag-grid engaged

Thanks for your collaboration!

**Comment by gportela85** [comment]
@lounsbrough Thanks for submitting this PR but merging this would actually break our build as is. This PR is also updating files within the `dist` folder.

We are already tracking a ticket for this issue and it will be fixed in the next release.

**Comment by lounsbrough** [comment]
@gportela85 thanks for the update, much appreciated!

**Pull request closed without merging**
