### PR TITLE
Fix misspelling of community

### PR DESCRIPTION
**Pull request by Stargator**
Noticed when following the directions and copying commands that there was a misspelling. So instead of ignoring it, I would like to fix it.

### CODE REVIEW

**Comment by Stargator** [comment]
I think this should be addressed. It's minor, but it affects anyone who's trying to duplicate three steps

**Comment by WuglyakBolgoink** [comment]
up

**Comment by Stargator** [comment]
Pinging @gportela85 and @seanlandsman just to see if there's anything I can do to make this easier

**Comment by WuglyakBolgoink** [comment]
ping

**Comment by gportela85** [comment]
@Stargator please, submit PR's against `latest` instead of `master`

**Comment by Stargator** [comment]
Ok, will do

**Pull request closed without merging**
