### PR TITLE
AG-6845 - Add Vue 3 Standalone Charts getting started example

### PR DESCRIPTION
**Pull request by manapeirov**
PR for: https://ag-grid.atlassian.net/browse/AG-6845

### CODE REVIEW

**Review by alantreadway — APPROVED** [review]
LGTM - can you check with @seanlandsman about whether we need to do anything special for publishing these CodeSandbox examples? (The StackBlitz ones all used to be under a shared robot account)

**Comment by manapeirov** [comment]
@alantreadway PTAL

**Comment by seanlandsman** [comment]
Probably not worth changing the examples but I'd inline the config where possible - for example:

```
  data: function () {
    return {
      options: {
        data: [
          {
            beverage: "Coffee",
            Q1: 450,
            Q2: 560,
            Q3: 600,
            Q4: 700,
          },
          {
            beverage: "Tea",
            Q1: 270,
            Q2: 380,
            Q3: 450,
            Q4: 520,
          },
          {
            beverage: "Milk",
            Q1: 180,
            Q2: 170,
            Q3: 190,
            Q4: 200,
          },
        ],
        title: { text: "Beverage Expenses" },
        subtitle: { text: "per quarter" },
        padding: {
          top: 40,
          right: 40,
          bottom: 40,
          left: 40,
        },
        series: [
          { type: "column", xKey: "beverage", yKey: "Q1", stacked: true },
          { type: "column", xKey: "beverage", yKey: "Q2", stacked: true },
          { type: "column", xKey: "beverage", yKey: "Q3", stacked: true },
          { type: "column", xKey: "beverage", yKey: "Q4", stacked: true },
        ],
        legend: { spacing: 40 },
      },
    };
  },
```

I accept that this is entirely subjective though...

**Comment by alantreadway** [comment]
LGTM - I agree with @seanlandsman's assessment regarding the in-lining, but let's tackle that in a follow-up since it's a minor tweak and we need to focus on making sure Cross Lines is solid for the code-freeze?

**Review by alantreadway — APPROVED** [review]

**Pull request merged**
