### PR TITLE
Usual Rows can be full-width

### PR DESCRIPTION
**Pull request by abadakhshan**
Add **rowFillExtraWidth** option to grid to handle this issue

#4302

### CODE REVIEW

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for submitting this PR, at the moment we don’t have a safe mechanism to automatically merge these, but we do this manually instead.

At this stage, your PR is being considered, we should update you as soon as possible, if this PR were to be approved note that we would do this in our end manually and we would close this, but you would get your changes effectively into our source code.

At the moment this is going to be flagged with ag-grid engaged

Thanks for your collaboration!

**Comment by ceolter** [comment]
I don't see how this fixes anything?
All that was done is a new property put into GridOptions, but I don't see any code uses this property.

Also the PR has lots of formatting changes, making it difficult to see what the intended changes are.

**Comment by ceolter** [comment]
closing until code doesn't include formatting changes and it's more clear what this is doing

**Comment by abadakhshan** [comment]
Hello @ceolter 

This PR is responded to issue #4302.

It adds a property to GridOptions (rowFillExtraWidth) and based on this property do something to fill extra width.
Add [fillExtraWidth ](https://github.com/abadakhshan/ag-grid/blob/430575b6d314701d9e970bbd8bb585a979fdb47b/community-modules/core/src/ts/columnController/columnController.ts#L3508) method to `coloumnController `and call it when needed.

All formats are based on https://github.com/ag-grid/ag-grid/blob/master/.prettierrc.
If it is incorrect let me know where is the correct prettier config for formatting.

Thank you.

**Comment by gportela85** [comment]
@abadakhshan The `prettier` plugin is not in use at the moment. As a general rule when submitting PRs, do not change code styling. Submit a PR containing changes that are relevant to the bugfix/feature only. It's also better for visibility of what is actually being changed.

**Comment by abadakhshan** [comment]
Ok.
I will update this PR.

Thank you.

**Comment by abadakhshan** [comment]
Hello @gportela85, @ceolter 

I created another [PR](https://github.com/ag-grid/ag-grid/pull/4382)

Thank you for your advice.

**Pull request closed without merging**
