### PR TITLE
Documentation update for correct version of AG-Grid

### PR DESCRIPTION
**Pull request by pdemro**
Per https://www.npmjs.com/package/ag-grid

image

### CODE REVIEW

**Comment by pdemro** [comment]
Bump

**Comment by WuglyakBolgoink** [comment]
Bump

**Comment by WuglyakBolgoink** [comment]
ping

**Comment by kiril-matev** [comment]
Hello!

Thank you for submitting this.

We have added these two items to our backlog and we are tracking it with the following reference and description:
AG-4607 [Docs] Update NPMJS installation instructions to point to ag-grid-community
AG-4608 Add ascii_only flag for terser options to support UTF-8 restrictions

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

Thanks again for bringing this up with us.

Regards,

**Comment by makinggoodsoftware** [comment]
Hi,

These changes are going to be included in ag-grid.

Thanks for sending the PR!

**Pull request closed without merging**
