### PR TITLE
Add NPM keywords for search on npm site

### LINKED ISSUE #3360: Searching for library on NPM
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
[x] setup => update project setup
```

**Customers of ag-Grid**

If you are a customer you are entitled to use the ag-Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the ag-Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of ag-Grid, ag-grid staff will label your issue as managed-by-the-community. This means that ag-Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

**Expected behavior**

**Please tell us about your environment:**

* **ag-Grid version:** X.X.X

* **Browser:**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Searching on npmjs.org is frustrating because I have to remember the name of the package exactly. I would like to search for "ag grid react" like it was any other search engine.

### PR DESCRIPTION
**Pull request by mahcloud**
resolves #3360

### CODE REVIEW

**Comment by abominab** [comment]
Why on earth is this still open? Just merge it already!

**Comment by mahcloud** [comment]
@abominab do you know who I can reach out to that has merge permissions?

**Comment by abominab** [comment]
I'm guessing @ceolter probably does

**Comment by abominab** [comment]
Hey @seanlandsman, @makinggoodsoftware, @petyosi. Any of you care to get this merged?

**Pull request closed without merging**
